apiVersion: v1
kind: pod
metadata:
  name: mypod
  namespace: prod
  labels:
   app: mypod
spec:
 containers:
  name: my-containers
  namespace: prod
  image: nginx:latest
 ports:
  port: 80
  name: http
  protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
 - name: my-Service
   labels:
   app: my-Service
spec:
 type: ClusterIP
 selector: 
  app: mypod
 ports:
  - port: 80
    name: http
    protocol: TCP

---
apiVersion: v1
kind: Namespace
metadata:
 name: prod
 labels: 
  app: prod


